// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace TestMLML.Model
{
    public class ModelInput
    {
        [ColumnName("id"), LoadColumn(0)]
        public float Id { get; set; }


        [ColumnName("name"), LoadColumn(1)]
        public float Name { get; set; }


    }
}
